# Basic configuration
flyway.url=jdbc:snowflake://https://wq26854.ap-southeast-1.snowflakecomputing.com
flyway.initSql=USE ROLE ACCOUNTADMIN;USE WAREHOUSE COMPUTE_WH;USE DATABASE CICD_DEMO;USE SCHEMA UTIL;
flyway.locations=filesystem:sql

# Placeholders
flyway.placeholders.publicSchema=PUBLIC


