# This is a basic workflow to help you get started with Actions
name: CI_DEV
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  push:
    branches:
      - dev
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  migrate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev
    # container:
    #   image: flyway/flyway
    steps:
      - uses: actions/checkout@v3
      - name: Migrate flyway scripts
        run: |
            wget https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10.11.0/flyway-commandline-10.11.0-linux-x64.tar.gz
            tar -xzf flyway-commandline-10.11.0-linux-x64.tar.gz
            ls

            current_path=$(pwd)
            echo $current_path
            export PATH=$PATH:/$current_path/flyway-10.11.0/
            export JAVA_ARGS=--add-opens=java.base/java.nio=ALL-UNNAMED
            flyway -outOfOrder=true -url="${{ secrets.SNOWFLAKE_URL }}" -user="${{ secrets.SNOWFLAKE_USER }}" -password=${{ secrets.SNOWFLAKE_PASSWORD }} -configFiles=configs/dev.conf migrate
        shell: bash